print("                     .")
print("                    / V\\")
print("                  / `  /")
print("                 <<   |")
print("                 /    |")
print("               /      |")
print("             /        |")
print("           /    \  \ /")
print("          (      ) | |")
print("  ________|   _/_  | |")
print("<__________\______)\__)")
